[tool.black]
line-length = 79

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[tool.mypy]
explicit_package_bases = true
ignore_missing_imports = true
mypy_path = "src"
namespace_packages = true
strict = true
